const express = require("express");
const router = express.Router();
const admin = require("../Controllers/adminController");

router.get("/", admin.sessionCheck, admin.login);
router.post("/loginsub", admin.loginSub);
router.get("/userManagement", admin.sessionCheck, admin.userManagement);
router.post("/deleteUser", admin.sessionCheck, admin.deleteUser);
router.post("/search", admin.sessionCheck, admin.search);
router.get("/active", admin.sessionCheck, admin.active);
router.get("/block", admin.sessionCheck, admin.block);
router.get("/addUser", admin.sessionCheck, admin.addUser);
router.post("/addUserSub", admin.sessionCheck, admin.addUserSub);
router.post("/editUser", admin.sessionCheck, admin.editUser);
router.post("/editUserSub", admin.sessionCheck, admin.editUserSub);
router.get("/category", admin.sessionCheck, admin.category);
router.get("/addCategory", admin.sessionCheck, admin.addCategory);
router.post("/addCategorySub", admin.sessionCheck, admin.addCategorySub);
router.post("/deleteCategory", admin.sessionCheck, admin.deleteCategory);
router.post("/categorySearch", admin.sessionCheck, admin.categorySearch);
router.post("/editCategory", admin.sessionCheck, admin.editCategory);
router.post("/editCategorySub", admin.sessionCheck, admin.editCategorySub);
router.get("/productManagement", admin.sessionCheck, admin.productManagement);
router.get("/addProduct", admin.sessionCheck, admin.addProduct);
router.post("/addProductSub", admin.sessionCheck, admin.addProductSub);
router.get("/instock", admin.sessionCheck, admin.instock);
router.get("/outofstock", admin.sessionCheck, admin.outofstock);
router.post("/productSearch", admin.sessionCheck, admin.productSearch);
router.post("/deleteProduct", admin.sessionCheck, admin.deleteProduct);
router.post("/editProduct", admin.sessionCheck, admin.editProduct);
router.post("/editProductSub", admin.sessionCheck, admin.editProductSub);
router.get("/orderManagement", admin.sessionCheck, admin.orderManagement);
router.put("/api/orderStatus", admin.sessionCheck, admin.orderStatus);
router.get("/pending", admin.sessionCheck, admin.pending);
router.get("/delivered", admin.sessionCheck, admin.delivered);
router.get("/cancelled", admin.sessionCheck, admin.cancelled);
router.post("/orderSearch", admin.sessionCheck, admin.orderSearch);
router.post("/api/addCoupon", admin.sessionCheck, admin.addCoupon);
router.patch("/api/editCoupon", admin.sessionCheck, admin.editCoupon);
router.get("/report", admin.sessionCheck, admin.report);
router.post("/report", admin.sessionCheck, admin.report);
router.get("/offers", admin.sessionCheck, admin.offer);
router.get("/api/download", admin.sessionCheck, admin.download);
router.get("/logOut", admin.sessionCheck, admin.logOut);

module.exports = router;
